version: "3"
services:
  frontend:
    image: node:18.14.2-alpine3.17
    env_file: ./frontend.env
    working_dir: /app
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ../frontend:/app
    tty: true
    restart: always
    command: >
      ash -c "npm install &&
      npm run build &&
      npm run production"

  backend:
    image: node:18.14.2-alpine3.17
    env_file: ./backend.env
    working_dir: /app
    command: npm start
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ../backend:/app
    tty: true
    command: >
      ash -c "npm install &&
      npm start"
